### ISSUE TITLE
document the API

### ISSUE THREAD

**Issue by gbolo** [gbolo/aws-power-toggle#16]
we need API documentation to aid in web UI development

**Comment by gbolo** [comment]
@kgeorgiou this should help out, will get it done tonight. No swagger though, just manual markdown :)

**Comment by gbolo** [comment]
this will be done against new API defined in #17

**Comment by gbolo** [comment]
@kgeorgiou please see the new documentation for the redesigned API: https://github.com/gbolo/aws-power-toggle/tree/api_redesigned#api-documentation

**Comment by kgeorgiou** [comment]
Looks good, my only comment:

```
POST /api/v1/instance/{instance-id}/stop # triggers a shutdown of a single instance
POST /api/v1/instance/{instance-id}/start # triggers a startup of a single instance
```

Maybe instances should be namespaced under the env they belong? e.g:
```
POST /api/v1/env/{env-id}/instance/{instance-id}/stop
POST /api/v1/env/{env-id}/instance/{instance-id}/start
```
It's a bit verbose but will avoid any `instance-id` collisions (is that possible to happen?)

**Comment by gbolo** [comment]
The instance `id` is guaranteed to be unique (unless of hash collision) because the following information is included into the hash already:

```
// compute a unique identifier for this instance
//   InstanceId is already unique, but this will make ids consistent
//   in case we add other cloud providers
cachedTable[i].Instances[c].Id = ComputeId(
	cachedTable[i].Provider,
	cachedTable[i].Region,
	instance.InstanceId,
)
```

`ComputeId` returns the first 12 characters from a SHA1 hash of the combined input string(s). I guess because of the truncating, it slightly increases the chances of a collision, but I think its very unlikely.

**Comment by kgeorgiou** [comment]
Oh ok, I had the impression that the instance-id is something you'd get from the vendor so I had in mind the scenario an id collision between different vendors.
