### ISSUE TITLE
add a confirmation prompt when shutting down environment

### ISSUE THREAD

**Issue by gbolo** [gbolo/aws-power-toggle#40]
Perhaps an "are you sure" prompt would help minimise possible accidental shutdowns of environments

**Comment by ahmedsajid** [comment]
Also entering environment name adds another level of sanity.

**Comment by dzhoou** [comment]
I think showing the environment name on the dialog is good enough ("Are you sure to shut down environment X?")

**Comment by gbolo** [comment]
@dzhoou that sounds good

**Comment by kgeorgiou** [comment]
Yes, great idea 👍 I'll work on it.

**Comment by gbolo** [comment]
@kgeorgiou you want this for release 3.2 or should we push this for release 3.3?

**Comment by kgeorgiou** [comment]
@gbolo 3.3. Unless I manage to open a PR by tonight.
