### ISSUE TITLE
display full list of instances in web UI

### ISSUE THREAD

**Issue by gbolo** [gbolo/aws-power-toggle#5]
since there already is an API endpoint that provides a list of instances per environment, perhaps we can work this into the web UI

**Comment by kgeorgiou** [comment]
Can we also power on/off instances individually?

**Comment by gbolo** [comment]
> Can we also power on/off instances individually?

Interesting suggestion. Backend API does not currently support that, but we can add it as a future enhancement. Open an issue to track it

**Comment by kgeorgiou** [comment]
Opened #15

**Comment by gbolo** [comment]
Closed via #25
