### ISSUE TITLE
CORS  'Access-Control-Allow-Origin' errors when integrating some AWS resources.

### ISSUE THREAD

**Issue by AlexMontesinos** [gbolo/aws-power-toggle#64]
Hi team,

this issue could be not particular to the tool but I need to resolve it through the code.

Im receiving:

Access to XMLHttpRequest at 'https://auth4.bricks.guru/oauth2/authorize?client_id=65bguc52sls6jt26quichoia46&redirect_uri=https%3A%2F%2Fptg.bricks.guru%2Foauth2%2Fidpresponse&response_type=code&scope=openid&state=4CO%2B3WCA59I3R8sKSLIea9ijRh89Lts2yoskelOul9q8mTRQVlosJSckYuj3WMsA5dcymJHcy5AWDpkb24SORZZ3gx6b97mc0Vu7rP0ls6rxp7c6apZCmRYcSKUD0CVEj2yDFvGQR1lVI7D5CT5TVhsUBuEHeooKtydfJ%2FOPRozJHpz71XHK9y7VjoYdPYOGFB8k8FqZkqRAeKF7NBP6ralAbbIDgUSNoHw%3D' (redirected from 'https://ptg.bricks.guru/api/v1/env/details') from origin 'https://ptg.bricks.guru' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

The type of alb I use to access this tool is internal so for quickly test I can even set Access-Control-Allow-Origin *

I tried through adding function

func enableCors(w *http.ResponseWriter) {
	(*w).Header().Set("Access-Control-Allow-Origin", "*")
}

and in each function

func handlerVersion(w http.ResponseWriter, req *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	enableCors(&w)

	fmt.Fprint(w, getVersionResponse())
}

that's all I modified as Im not a go developer, actually Im not developer. Imwondering If you can help to find the easy way to add the 
Access-Control-Allow-Origin * header to avoid the issue.

Thanks in advance!

**Comment by gbolo** [comment]
Hi @AlexMontesinos ,

Judging by the error message you posted, it would seem like you would need to configure the CORS header on the auth4.bricks.guru site. This would make sense to me, since power-toggle javascript only makes calls to it's own domain and not some external one...
